version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: pms-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    container_name: pms-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/progress_monitoring
      - JWT_SECRET=change_me_in_prod
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - CLIENT_URL=http://localhost:3000
      - MODEL_OUTPUT_PATH=/app/../model_simulation/output/progress_data.json
    depends_on:
      - mongo
    volumes:
      - ./model_simulation/output:/app/../model_simulation/output
      - backend-uploads:/app/uploads
  frontend:
    build: ./frontend
    container_name: pms-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  mongo-data:
  backend-uploads:

